use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

target 'MoyaCache_Example' do
  pod 'MoyaCache', :path => '../'
  pod 'Cache'
  pod 'CleanJSON'

  target 'MoyaCache_Tests' do
    inherit! :search_paths

    
  end
end
